---
title: "Chapter 16"
engine: knitr
---

```{r}
pacman::p_load(tidyverse, tidymodels)
set.seed(1234)
```

```{r}
'kbo_team_batting.csv' %>%
  read_csv() %>%
  as_tibble() -> team_batting
```

```{r}
team_batting %>%
  mutate(
    runs = r / tpa,
    avg = h / ab,
    obp = (h + bb + hbp) / (ab + bb + hbp + sf),
    slg = (h + `2b` + 2 * `3b` + 3 * hr) / ab
  ) -> team_batting
```

```{r}
team_batting %>%
  select(avg, obp, slg) %>%
  cor()
```

```{r}
pacman::p_load(car)
```

```{r}
team_batting %>%
  lm(runs ~ avg + obp + slg, data = .) %>%
  vif()
```

```{r}
team_batting %>%
  lm(runs ~ avg + obp + slg, data = .) %>%
  summary()
```

```{r}
team_batting %>%
  lm(runs ~ obp + slg, data = .) %>%
  summary()
```

```{r}
team_batting %>%
  select(obp, slg) %>%
  pivot_longer(obp:slg) %>%
  group_by(name) %>%
  summarise(mean = mean(value), sd = sd(value))
```

```{r}
team_batting %>%
  select(obp, slg) %>%
  pivot_longer(obp:slg) %>%
  ggplot((aes(x = value, fill = name))) +
  geom_histogram(
    position = 'identity',
    binwidth = .01,
    alpha = .75,
    color = 'white'
  )
```

```{r}
team_batting %>%
  mutate(
    obp_z = (obp - mean(obp)) / sd(obp),
    slg_z = (slg - mean(slg)) / sd(slg),
    .before = g
  ) -> team_batting
```

```{r}
team_batting %>%
  lm(runs ~ obp_z + slg_z, data = .) %>%
  summary()
```

```{r}
pacman::p_load(vip)
```

```{r}
team_batting %>%
  lm(runs ~ obp + slg, data = .) %>%
  vi()
```

```{r}
team_batting %>%
  lm(runs ~ obp + slg, data = .) %>%
  vip() +
  geom_text(aes(label = Importance))
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm')
```

```{r}
show_engines('linear_reg')
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm') %>%
  fit(runs ~ obp + slg, data = team_batting)
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm') %>%
  fit(runs ~ obp + slg, data = team_batting) %>%
  tidy()
```

```{r}
team_batting %>%
  initial_split() -> team_batting_split

team_batting_split
```

```{r}
team_batting %>%
  initial_split(prop = .7) -> team_batting_split

team_batting_split
```

```{r}
team_batting_split %>%
  training() -> team_batting_training
```

```{r}
team_batting_split %>%
  testing() -> team_batting_testing
```

```{r}
team_batting_training
```

```{r}
team_batting_testing
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm') %>%
  fit(runs ~ obp + slg, data = team_batting_training) -> team_batting_fit
```

```{r}
team_batting_fit %>%
  predict(new_data = team_batting_testing)
```

```{r}
team_batting_fit %>%
  predict(new_data = team_batting_testing) %>%
  mutate(truth = team_batting_testing$runs)
```

```{r}
team_batting_fit %>%
  predict(new_data = team_batting_testing) %>%
  mutate(truth = team_batting_testing$runs) %>%
  rmse(truth = truth, estimate = .pred)
```

```{r}
team_batting_fit %>%
  predict(new_data = team_batting_training) %>%
  mutate(truth = team_batting_training$runs) %>%
  rmse(truth = truth, estimate = .pred)
```

```{r}
'kovo_sets_results.csv' %>%
  read_csv() %>%
  as_tibble() -> kovo_sets_results

kovo_sets_results
```

```{r}
kovo_sets_results %>%
  mutate(남녀부 = as_factor(남녀부)) -> kovo_sets_results
```

```{r}
kovo_sets_results %>%
  ggplot(aes(x = 리시브_효율, y = 승률, color = 남녀부)) +
  geom_point() +
  geom_smooth(method = 'lm', se = FALSE)
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm') %>%
  fit(승률 ~ 리시브_효율 * 남녀부, data = kovo_sets_results) %>%
  tidy()
```

```{r}
kovo_sets_results %>%
  filter(남녀부 == '여') %>%
  specify(승률 ~ 리시브_효율) %>%
  hypothesize(null = 'independence') %>%
  generate(1000, type = 'permute') %>%
  calculate(stat = 'slope') %>%
  visualize() +
  shade_p_value(obs_stat = -.013, direction = 'two-sided')
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm') %>%
  fit(
    승률 ~ 세트당_서브 + 리시브_효율 + 공격_효율 + 세트당_블로킹 + 세트당_디그,
    data = kovo_sets_results %>% filter(남녀부 == '남')
  ) %>%
  tidy()
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm') %>%
  fit(
    승률 ~ 세트당_서브 + 공격_효율 + 세트당_블로킹 + 세트당_디그,
    data = kovo_sets_results %>% filter(남녀부 == '남')
  ) %>%
  tidy()
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm') %>%
  fit(
    승률 ~ 세트당_서브 + 공격_효율 + 세트당_블로킹 + 세트당_디그,
    data = kovo_sets_results %>% filter(남녀부 == '남')
  ) %>%
  vi()
```

```{r}
linear_reg() %>%
  set_engine(engine = 'lm') %>%
  fit(
    승률 ~ 세트당_서브 + 리시브_효율 + 공격_효율 + 세트당_블로킹 + 세트당_디그,
    data = kovo_sets_results %>% filter(남녀부 == '여')
  ) %>%
  tidy()
```

