---
jupyter:
  jupytext:
    cell_metadata_filter: '-all'
    encoding: '# -*- coding: utf-8 -*-'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.19.5
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
pacman::p_load(tidyverse, tidymodels)

set.seed(1234)
```

```{r}
'cheonan_attendance.csv' %>% 
  read.csv() %>% 
  as_tibble() -> cheonan_attendance
```

```{r}
cheonan_attendance %>% 
  glimpse()
```

```{r}
cheonan_attendance %>%
  summarise(여성비율 = mean(성별 == '여'))
```

```{r}
cheonan_attendance %>%
  rep_sample_n(reps = 10,
               size = 20,
               replace = TRUE) %>% 
  group_by(replicate) %>% 
  summarise(여성비율 = mean(성별 == '여'),
            .groups='drop') -> cheonan_sample
```

```{r}
cheonan_sample %>% 
  summarise(결과 = 여성비율 %>% mean())
```

```{r}
cheonan_sample %>% 
  select('여성비율') %>% 
  rep_sample_n(reps = 1000,
               size = 20,
               replace = TRUE) -> cheonan_sample_bootstrap
```

```{r}
cheonan_sample_bootstrap %>% 
  summarise(여성비율_평균 = mean(여성비율)) %>% 
  summarise(결과 = 여성비율_평균 %>% mean())
```

```{r}
cheonan_sample %>%
  ggplot(aes(x = 여성비율)) +
  geom_histogram(binwidth = .05, fill = 'gray75', color = 'white')
```

```{r}
cheonan_sample_bootstrap %>% 
  summarise(여성비율_평균 = mean(여성비율)) %>% 
  ggplot(aes(x = 여성비율_평균)) + 
  geom_histogram(binwidth = .01, fill = 'gray75', color = 'white')
```

```{r}
cheonan_sample_bootstrap %>%
  summarise(여성비율_평균 = mean(여성비율)) %>%
  summarise(low = quantile(여성비율_평균, .025),
            high = quantile(여성비율_평균, .975))
```

```{r}
cheonan_sample %>% 
  specify(response = 여성비율) 
```

```{r}
cheonan_sample %>% 
  specify(response = 여성비율) %>% 
  class()
```

```{r}
cheonan_sample %>%
  specify(response =  여성비율) %>%
  generate(reps = 1000, type = 'bootstrap')
```

```{r}
cheonan_sample %>%
  specify(response =  여성비율) %>%
  generate(reps = 1000, type = 'bootstrap') %>%
  calculate(stat = 'mean')
```

```{r}
cheonan_sample %>%
  specify(response =  여성비율) %>%
  generate(reps = 1000, type = 'bootstrap') %>%
  calculate(stat = 'mean') -> cheonan_bootstrap

cheonan_bootstrap %>% 
  visualize()
```

```{r}
cheonan_bootstrap %>% 
  get_confidence_interval()
```

```{r}
cheonan_bootstrap %>% 
  get_confidence_interval() -> ci_endpoints
```

```{r}
cheonan_bootstrap %>% 
  get_confidence_interval(level = .9)
```

```{r}
cheonan_bootstrap %>% 
  visualize() +
  shade_confidence_interval(
    endpoints = ci_endpoints
  )
```

```{r}
cheonan_bootstrap %>% 
  visualize() +
  shade_confidence_interval(
    endpoints = ci_endpoints,
    color = 'gray75', fill = 'gray75', size=0
  )
```

```{r}
cheonan_bootstrap %>% 
  get_confidence_interval(type = 'se', point_estimate = .570)
```

```{r}
cheonan_bootstrap %>%
  visualize() +
  shade_confidence_interval(
    endpoints = ci_endpoints,
    color = 'gray75', fill = 'gray75', size = 0)+
  geom_vline(
    xintercept = c(.522, .618),
    color = 'darkorange',
    linetype = 'dashed',
    lwd = 1
  )
```

