---
title: "Chapter 6"
engine: knitr
---

```{r}
rm(list=ls())
```

```{r}
pacman::p_load(tidyverse)
```

```{r}
tribble(
  ~연도, ~이름, ~홈런, ~팀,
  2003, '이승엽', 56, '삼성',
  1999, '이승엽', 54, '삼성',
  2003, '심정수', 53, '현대',
  2015, '박병호', 53, '넥센',
  2014, '박병호', 52, '넥센',
  2015, '나바로', 48, '삼성',
  2002, '이승엽', 47, '삼성',
  2015, '테임즈', 47, 'NC',
  2020, '로하스', 47, 'KT',
  2002, '심정수', 46, '현대',
) -> 홈런
```

```{r}
tribble(
  ~팀, ~애칭,
  '넥센', '히어로즈',
  '두산', '베어스',
  '롯데', '자이언츠',
  '삼성', '라이온즈',
  '한화', '이글스',
  'KIA', '타이거즈',
  'KT', '위즈',
  'LG', '트윈스',
  'NC', '다이노스',
  'SK', '와이번스'
) -> 팀
```

```{r}
홈런 %>% inner_join(팀)
```

```{r}
홈런 %>% left_join(팀)
```

```{r}
홈런 %>% right_join(팀)
```

```{r}
홈런 %>% full_join(팀)
```

```{r}
홈런 %>% semi_join(팀)
```

```{r}
홈런 %>% anti_join(팀)
```

```{r}
tribble(
  ~구단, ~애칭,
  '넥센', '히어로즈',
  '두산', '베어스',
  '롯데', '자이언츠',
  '삼성', '라이온즈',
  '한화', '이글스',
  'KIA', '타이거즈',
  'KT', '위즈',
  'LG', '트윈스',
  'NC', '다이노스',
  'SK', '와이번스'
) -> 팀
```

```{r}
홈런 %>% left_join(팀, by = c('팀' = '구단'))
```

```{r}
'data/international_soccer_matches_results.csv' %>% 
  read_csv() %>% 
  as_tibble() -> results

results
```

```{r}
results %>% 
  glimpse()  
```

```{r}
results %>%
  select(
    date,
    team = away_team,
    opponent = home_team,
    team_score = away_score,
    opponent_score = home_score,
    tournament:last_col()
  ) -> results_away

results_away
```

```{r}
tribble(
  ~a, ~b, ~c,
  1, 2, 3,
) -> tbl1

tbl1
```

```{r}
tribble(
  ~a, ~b, ~c,
  4, 5, 6
) -> tbl2

tbl2
```

```{r}
tbl1 %>% 
  bind_rows(tbl2)
```

```{r}
results %>%
  rename(
    team = home_team,
    opponent = away_team,
    team_score = home_score,
    opponent_score = away_score
  ) %>%
  bind_rows(results_away) -> results

results
```

```{r}
results %>%
  mutate(
    win = ifelse(team_score > opponent_score, 1, 0),
    draw = ifelse(team_score == opponent_score, 1, 0),
    lose = ifelse(team_score < opponent_score, 1, 0)
  ) %>%
  group_by(team) %>%
  summarise(
    wins = sum(win),
    draws = sum(draw),
    loses = sum(lose),
    matches = wins + draws + loses,
    win_percent = wins / matches,
    .groups = 'drop'
  ) %>%
  arrange(-wins)
```

```{r}
results %>%
  mutate(
    win = ifelse(team_score > opponent_score, 1, 0),
    draw = ifelse(team_score == opponent_score, 1, 0),
    lose = ifelse(team_score < opponent_score, 1, 0)
  ) %>%
  group_by(team) %>%
  summarise(
    wins = sum(win),
    draws = sum(draw),
    loses = sum(lose),
    matches = wins + draws + loses,
    win_percent = wins / matches,
    .groups = 'drop'
  ) %>%
  arrange(-win_percent)
```

```{r}
results %>%
  mutate(
    win = ifelse(team_score > opponent_score, 1, 0),
    draw = ifelse(team_score == opponent_score, 1, 0),
    lose = ifelse(team_score < opponent_score, 1, 0)
  ) %>%
  group_by(team, opponent) %>%
  summarise(
    wins = sum(win),
    draws = sum(draw),
    loses = sum(lose),
    matches = wins + draws + loses,
    win_percent = wins / matches,
    .groups = 'drop'
  ) %>%
  arrange(-wins)
```

```{r}
results %>%
  mutate(
    win = ifelse(team_score > opponent_score, 1, 0),
    draw = ifelse(team_score == opponent_score, 1, 0),
    lose = ifelse(team_score < opponent_score, 1, 0)
  ) %>%
  group_by(team, opponent) %>%
  summarise(
    wins = sum(win),
    draws = sum(draw),
    loses = sum(lose),
    matches = wins + draws + loses,
    win_percent = wins / matches,
    .groups = 'drop'
  ) %>%
  filter(team == 'South Korea') %>%
  arrange(-wins)
```

```{r}
'data/fifa_ranking.csv' %>% 
  read_csv() %>% 
  as_tibble() -> fifa_ranking
```

```{r}
fifa_ranking %>% 
  glimpse()
```

```{r}
fifa_ranking %>% 
  filter(country_full == 'South Korea')
```

```{r}
fifa_ranking %>% 
  filter(country_full == 'Korea Republic')
```

```{r}
results %>%
  filter(date >= '1993-08-08') %>%
  select(team) %>%
  distinct() -> results_countries

results_countries
```

```{r}
fifa_ranking %>%
  select(country_full, country_abrv) %>%
  distinct() -> fifa_ranking_countries

fifa_ranking_countries
```

```{r}
results_countries %>%
  left_join(fifa_ranking_countries,
            by = c('team' = 'country_full')) %>%
  filter(is.na(country_abrv) == TRUE) -> countries_to_match

countries_to_match
```

```{r}
pacman::p_load(countrycode)
```

```{r}
c('South Korea', 'Korea Republic') %>%
  countrycode(origin = 'country.name',
              destination = 'iso3c')
```

```{r}
tribble(
  ~x, ~y, ~z,
  8, 1, 6,
  3, 5, 7,
  4, 9, 2,
) %>% 
  mutate(sum = sum(x, y, z))
```

```{r}
tribble(
  ~x, ~y, ~z,
  8, 1, 6,
  3, 5, 7,
  4, 9, 2,
) %>% 
  rowwise() %>%
  mutate(sum = sum(x, y, z))

countries_to_match %>%
  rowwise() %>%
  mutate(country_abrv =
           countrycode(team,
                       origin = 'country.name',
                       destination = 'iso3c')) -> country_codes_result
```

```{r}
results_countries %>%
  left_join(fifa_ranking_countries,
            by = c('team' = 'country_full')) %>% 
  bind_rows(country_codes_result) %>% 
  drop_na() -> country_code_result

country_code_result
```

```{r}
results %>% 
  filter(date >= '1993-08-08') %>%
  left_join(country_code_result) %>% 
  left_join(fifa_ranking,
            by = c('country_abrv', 'date' = 'rank_date')) %>% 
  select(id:last_col())
```

```{r}
results %>% 
  filter(date >= '1993-08-08') %>%
  left_join(country_code_result) %>% 
  left_join(fifa_ranking,
            by = c('country_abrv', 'date' = 'rank_date')) %>% 
  drop_na()
```

```{r}
results %>%
  filter(date >= '1993-08-08') %>%
  left_join(country_code_result) %>%
  rename(team_abrv = country_abrv) %>%
  left_join(country_code_result,
            by = c('opponent' = 'team')) %>%
  rename(opponent_abrv = country_abrv)
```

```{r}
results %>%
  filter(date > '1993-08-08') %>%
  left_join(country_code_result) %>%
  rename(team_abrv = country_abrv) %>%
  left_join(country_code_result,
            by = c('opponent' = 'team')) %>%
  rename(opponent_abrv = country_abrv) %>%
  drop_na() %>%
  write.csv('soccer_matches_results_in_progress.csv')
```

