---
title: "Chapter 2"
engine: knitr
---

```{r}
library(dplyr)
```

```{r}
mtcars[sample(1:nrow(mtcars), 10), ]
```

```{r}
mtcars %>%
  sample_n(10)
```

```{r}
# install.packages('tidyverse')

library('tidyverse')
```

```{r}
# install.packages('pacman')

pacman::p_load(tidyverse, tidymodels)
```

```{r}
batting <- read_csv('data/kbo_batting_qualified.csv')
batting
```

```{r}
batting <- read_csv(
  'data/kbo_batting_qualified.csv',
  locale = locale('ko', encoding = 'utf-8'),
  show_col_types = FALSE
)
glimpse(batting)
```

```{r}
batting
```

```{r}
class(batting)
```

```{r}
batting <- read_csv('data/kbo_batting_qualified.csv')
```

```{r}
batting <- as_tibble(batting)
```

```{r}
class(batting)
```

```{r}
df1 <- data.frame(x = c(1, 2, 3), y = c(4, 5, 6))
df1
```

```{r}
df2 <- tribble(
  ~x ,
  ~y ,
   #---|---
  1 ,
   4 ,
   2 ,
   5 ,
   3 ,
   6
)
df2
```

```{r}
df2 <- read_csv(textConnection(
  "
x, y
1, 4
2, 5
3, 6
"
))
df2
```

```{r}
1:10 %>% sum()
```

```{r}
batting %>%
  print(n = 20)
```

```{r}
'data/kbo_batting_qualified.csv' %>%
  read_csv() %>%
  as_tibble() -> batting
batting
```
