---
title: "Chapter 1"
engine: knitr
---

```{r}
print("Hello, World!")
```

```{r}
1 + 2
```

```{r}
object <- 1 + 2

print(object) #object를 출력하라
```

```{r}
object
```

```{r}
ls()
```

```{r}
rm(object) #object 지우기
```

```{r}
rm(list = ls())
```

```{r}
z <- y <- x <- 1 + 2
```

```{r}
x
```

```{r}
y
```

```{r}
z
```

```{r}
c(x, y, z)
```

```{r}
c(1, 2, 3)
```

```{r}
1:10
```

```{r}
seq(1, 10, 2)
```

```{r}
add_one <- function(x) {
  x + 1
}

add_one(2)
```

```{r}
df1 <- data.frame(x = c(1, 2, 3), y = c(4, 5, 6))

df1
```

```{r}
class(df1)
```

```{r}
df1$x
```

```{r}
df1$z <- c(7, 8, 9)
```

```{r}
df1[1, ] #첫 행을 출력하라
```

```{r}
df1[, 1] #첫 열을 출력하라
```

```{r}
df1[2, 2] #두 번째 행, 두 번째 열을 출력하라
```

```{r}
1 == 1
```

```{r}
1 == 2
```

```{r}
df1$x == 1
```

```{r}
df1[df1$x == 1, ]
```

```{r}
df1[, df1$x == 2]
```

```{r}
class(df1)
```

```{r}
getwd()
```

```{r}
batting <- read_csv(
  'https://github.com/bigkini/kindeR/blob/main/kbo_batting_qualified.csv'
)
```

```{r}
batting <- read_csv('data/kbo_batting_qualified.csv')
```

```{r}
class(batting)
```

```{r}
str(batting)
```

```{r}
head(batting)
```

```{r}
tail(batting, 5)
```

```{r}
head(batting$avg, 5)
```

```{r}
mean(batting$avg)
```

```{r}
sd(batting$avg)
```

```{r}
summary(batting)
```

```{r}
summary(0:100)
```

```{r}
length(ls('package:base'))
```

```{r}
?ls
```

```{r}
args(rm)
```
