---
title: "Chapter 4"
engine: knitr
---

```{r}
pacman::p_load(tidyverse, here)
```

```{r}
here('data', 'kbo_team_batting.csv') %>% 
  read_csv() %>% 
  as_tibble() -> team_batting

team_batting
```

```{r}
team_batting %>%
  arrange(team)
```

```{r}
team_batting %>%
  arrange(team %>% desc())
```

```{r}
team_batting %>%
  arrange(team, year)
```

```{r}
team_batting %>%
  filter(year == 1982)
```

```{r}
team_batting[team_batting$year == 1982,]
```

```{r}
team_batting[1:6, ]
```

```{r}
team_batting %>%
  slice(1:6)
```

```{r}
team_batting[sample(1:nrow(team_batting), 5), ]
```

```{r}
team_batting %>% 
  sample_n(5)
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  arrange(hr %>% desc())
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  arrange(-hr)
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  select(year, team, h, `2b`, `3b`, hr)
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  relocate(year, .before = team)
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  relocate(g, .after = year)
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  select(season = year, team, h, `2b`, `3b`, hr)
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  select(year, team, h, `2b`, `3b`, hr) %>%
  select(-`3b`)
```

```{r}
team_batting %>% 
  filter(year == 1982) %>%
  select(bb:last_col())
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  select(2, 1, 7:10)
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  select(year, team, h:hr)
```

```{r}
team_batting %>%
  filter(year == 1982) %>%
  select(year, team, h:hr) %>% 
  mutate(tb = h + `2b` + 2 * `3b` + 3 * hr)
```

```{r}
team_batting %>%
  mutate(avg = h / ab) %>%
  select(year, team, avg)
```

```{r}
team_batting %>%
  transmute(year, team, avg = h / ab)
```

```{r}
team_batting %>%
  mutate(avg = h / ab, .keep = 'used')
```

```{r}
team_batting %>%
  mutate(avg = h / ab, .keep = 'unused')
```

```{r}
team_batting %>%
  mutate(avg = h / ab, .before = g)
```

```{r}
team_batting %>%
  group_by(year) %>%
  mutate(avg = sum(h) / sum(ab), .before = g)
```

```{r}
team_batting %>%
  group_by(year) %>%
  mutate(avg = h / ab, .before = g)
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(avg = sum(h) / sum(ab))
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(avg = sum(h) / sum(ab), .groups = 'drop')
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(avg = sum(h) / sum(ab), .groups = 'drop') %>%
  ggplot(aes(x = year, y = avg)) +
  geom_line()
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(avg = sum(h) / sum(ab), .groups = 'drop') %>%
  filter(year == 1999)
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(avg = sum(h) / sum(ab), .groups = 'drop') %>%
  arrange(-avg)
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(avg = sum(h) / sum(ab), .groups = 'drop') %>%
  filter(avg == max(avg))
```

```{r}
team_batting %>%
  mutate(
    avg = h / ab,
    obp = (h + bb + hbp) / (ab + bb + hbp + sf),
    slg = (h + `2b` + 2 * `3b` + 3 * hr) / ab,
    ops = obp + slg,
    .before = g
  )
```

```{r}
team_batting %>%
  mutate(
    avg = h / ab,
    obp = (h + bb + hbp) / (ab + bb + hbp + sf),
    slg = (h + `2b` + 2 * `3b` + 3 * hr) / ab,
    ops = obp + slg,
    .before = g
  ) %>%
  filter(ops >= 0.7 & hr < 70)
```

```{r}
team_batting %>%
  mutate(
    avg = h / ab,
    obp = (h + bb + hbp) / (ab + bb + hbp + sf),
    slg = (h + `2b` + 2 * `3b` + 3 * hr) / ab,
    ops = obp + slg,
    .before = g
  ) %>%
  filter(ops >= 0.7 & hr < 70) %>%
  summarise(count = n())
```

```{r}
team_batting %>%
  mutate(
    avg = h / ab,
    obp = (h + bb + hbp) / (ab + bb + hbp + sf),
    slg = (h + `2b` + 2 * `3b` + 3 * hr) / ab,
    ops = obp + slg,
    .before = g
  ) %>%
  filter(ops >= 0.7, hr < 70) %>%
  tally()
```

```{r}
team_batting %>%
  mutate(
    avg = h / ab,
    obp = (h + bb + hbp) / (ab + bb + hbp + sf),
    slg = (h + `2b` + 2 * `3b` + 3 * hr) / ab,
    ops = obp + slg,
    .before = g
  ) %>%
  filter(ops >= 0.7, hr < 70, year %in% 1991:2000)
```

```{r}
team_batting %>%
  mutate(
    avg = h / ab,
    obp = (h + bb + hbp) / (ab + bb + hbp + sf),
    slg = (h + `2b` + 2 * `3b` + 3 * hr) / ab,
    ops = obp + slg,
    .before = g
  ) %>%
  filter(ops >= 0.7, hr < 70, year %in% 1991:2000) %>%
  transmute(year, team, rg = r / g, sb = sb / g)
```

```{r}
team_batting %>%
  transmute(decades = if_else(year <= 1990, '1980',
                              if_else(
                                year <= 2000, '1990',
                                if_else(year <= 2010, '2000', '2010')
                              )),
            g, sh)
```

```{r}
team_batting %>%
  distinct(year) %>%
  mutate(
    decades = case_when(
      year <= 1990 ~ '1980',
      year <= 2000 ~ '1990',
      year <= 2010 ~ '2000',
      year <= 2020 ~ '2010'
    )
  )
```

```{r}
c(1, 1, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5) %>%
  as_tibble() %>%
  distinct()
```

```{r}
team_batting %>%
  mutate(
    decades = case_when(
      year <= 1990 ~ '1980',
      year <= 2000 ~ '1990',
      year <= 2010 ~ '2000',
      year <= 2020 ~ '2010'
    )
  ) %>%
  group_by(decades) %>%
  summarise(sh_mean = sum(sh) / sum(g))
```

```{r}
team_batting %>%
  mutate(
    decades = case_when(
      year <= 1990 ~ '1980',
      year <= 2000 ~ '1990',
      year <= 2010 ~ '2000',
      year <= 2020 ~ '2010'
    )
  ) %>%
  group_by(decades) %>%
  summarise(error_mean = e %>% sum() / g %>% sum())
```

```{r}
team_batting %>%
  group_by(team) %>%
  summarise(gidp = sum(gidp)) %>%
  arrange(-gidp) %>%
  head(3)
```

```{r}
team_batting %>%
  distinct(team)
```

```{r}
team_batting %>%
  mutate(
    team_id = fct_collapse(
      team,
      두산  = c('OB', '두산'),
      키움  = c('히어로즈', '넥센', '키움'),
      한화  = c('빙그레', '한화'),
      현대  = c('삼미', '삼미·청보', '청보', '태평양'),
      KIA = c('해태', '해태·KIA', 'KIA'),
      LG = c('LG', 'MBC'),
    ), .before = year
  ) 
```

```{r}
team_batting %>%
  mutate(
    team_id = fct_collapse(
      team,
      두산  = c('OB', '두산'),
      키움  = c('히어로즈', '넥센', '키움'),
      한화  = c('빙그레', '한화'),
      현대  = c('삼미', '삼미·청보', '청보', '태평양'),
      KIA = c('해태', '해태·KIA', 'KIA'),
      LG = c('LG', 'MBC'),
    )
  ) %>%
  group_by(team_id) %>%
  summarise(gidp = sum(gidp), .groups = 'drop') %>%
  arrange(-gidp)
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(batters = sum(batters) / sum(g))
```

```{r}
map(1:5, ~.x+1)
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(across(-team, ~sum(.x) / sum(g)), .groups = 'drop')
```

```{r}
team_batting %>%
  group_by(year) %>%
  summarise(across(-team, list(
    sum = ~sum(.x),
    mean = ~sum(.x) / sum(g))
    ), .groups = 'drop')
```

```{r}
letters
```

```{r}
letters[1:11]
```

```{r}
rep(1:3, 3)
```

```{r}
letters[1:11] %>%
  rep(c(64, 32, 16, 8, 4, 2, 1, 1, 1, 1, 1))
```

```{r}
letters[1:11] %>%
  rep(c(64, 32, 16, 8, 4, 2, 1, 1, 1, 1, 1)) %>%
  table()
```

```{r}
letters[1:11] %>%
  rep(c(64, 32, 16, 8, 4, 2, 1, 1, 1, 1, 1)) %>%
  fct_lump(3) %>%
  table()
```

```{r}
letters[1:11] %>%
  rep(c(64, 32, 16, 8, 4, 2, 1, 1, 1, 1, 1)) %>%
  fct_lump(3)
```

```{r}
letters[1:11] %>%
  rep(c(64, 32, 16, 8, 4, 2, 1, 1, 1, 1, 1)) %>%
  fct_lump(3, other_level = '??Ÿ') %>%
  table()
```

```{r}
letters[1:11] %>%
  rep(c(64, 32, 16, 8, 4, 2, 1, 1, 1, 1, 1)) %>%
  fct_lump(prop = .2)
```

```{r}
letters[1:11] %>%
  rep(c(64, 32, 16, 8, 4, 2, 1, 1, 1, 1, 1)) %>%
  fct_lump_min(2)
```

```{r}
here('data', 'kovo_team.csv') %>% 
  read_csv() %>% 
  as_tibble() -> kovo_team

kovo_team
```

```{r}
kovo_team %>%
  distinct(팀) %>%
  arrange(팀) %>% 
  pull()
```

```{r}
kovo_team %>%
  mutate(
    팀 = case_when(
      남녀부 == '남' & 팀 == '현대' ~ '현대캐피탈',
      남녀부 == '여' & 팀 == '현대' ~ '현대건설',
      TRUE ~  팀),
    팀_이름 = 팀,
    팀 = fct_collapse(
      팀,
      대한항공 = 'KAL',
      삼성화재 = '삼성',
      상무 = c('상무', '상무신협', '신협상무'),
      우리카드 = c('드림식스', '우리카드', '우리캐피탈'),
      한국전력 = c('한국전력', '한전', 'KEPCO', 'KEPCO45'),
      KB손해보험 = c('KB손보', 'LG', 'LIG', 'LIG손보'),
      OK금융그룹 = c('러시앤캐시', 'OK저축은행'),
      GS칼텍스 = 'GS',
      IBK기업은행 = 'IBK',
      KGC인삼공사 = c('인삼공사', 'KGC인삼공사', 'KT&G'),
      한국도로공사 = c('도공', '도로공사'),
      흥국생명 = '흥국'
    )
  ) -> kovo_team
```

```{r}
kovo_team %>% 
  distinct(시즌) %>% 
  pull()
```

```{r}
kovo_team %>% 
  mutate(시즌_이름=시즌,
              시즌=시즌 %>% str_sub(-4)) -> kovo_team

kovo_team
```

```{r}
kovo_team %>% 
  select(시즌, 팀, contains('공격종합'))
```

```{r}
kovo_team %>% 
  select(-contains('_'))
```

```{r}
kovo_team %>% 
  select(시즌, 팀, starts_with('세트'))
```

```{r}
kovo_team %>% 
  select(시즌, 팀, ends_with('세트당_평균'))
```

```{r}
tribble(
  ~x, ~y,
  1, 2,
) %>% 
  rename(z = x)
```

```{r}
kovo_team %>%
  select(시즌,  팀, ends_with('세트당_평균')) %>%
  rename(블로킹 =  블로킹_세트당_평균,
         서브 =  서브_세트당_평균)
```

```{r}
str_replace('블로킹_세트당_평균', '_세트당_평균', '')
```

```{r}
kovo_team %>% 
  select(시즌, 팀, ends_with('세트당_평균')) %>% 
  rename_with(~str_replace(., '_세트당_평균', ''))
```

```{r}
kovo_team %>%
  group_by(시즌, 남녀부) %>%
  summarise(리시브_효율 = (sum(리시브_정확) - sum(리시브_실패)) / sum(리시브_시도),
            .groups = 'drop') %>%
  ggplot(aes(x = 시즌, y = 리시브_효율, group = 남녀부, color = 남녀부)) +
  geom_line()
```

```{r}
kovo_team %>%
  group_by(남녀부, 시즌) %>%
  summarise(리시브_효율 = (sum(리시브_정확) - sum(리시브_실패)) / sum(리시브_시도)) %>%
  mutate(전_시즌 = lag(리시브_효율))
```

```{r}
kovo_team %>%
  group_by(남녀부, 시즌) %>%
  summarise(리시브_효율 = (sum(리시브_정확) - sum(리시브_실패)) / sum(리시브_시도)) %>%
  mutate(다음_시즌 = lead(리시브_효율)) %>%
  print(n = 17)
```

```{r}
kovo_team %>%
  group_by(남녀부, 시즌) %>%
  summarise(리시브_효율 = (sum(리시브_정확) - sum(리시브_실패)) / sum(리시브_시도)) %>% 
  mutate(차이 = 리시브_효율 - lag(리시브_효율))
```

```{r}
kovo_team %>%
  group_by(남녀부,  시즌) %>%
  summarise(리시브_효율  = (sum(리시브_정확) - sum(리시브_실패)) / sum(리시브_시도),
            .groups = 'drop') %>%
  mutate(차이 = 리시브_효율 -lag(리시브_효율)) %>%
  summarise(차이_평균 = mean(차이))
```

```{r}
kovo_team %>%
  group_by(남녀부, 시즌) %>%
  summarise(리시브_효율 = (sum(리시브_정확) - sum(리시브_실패)) / sum(리시브_시도),
            .groups = 'drop') %>%
  mutate(차이 = 리시브_효율 -lag(리시브_효율)) %>%
  summarise(차이_평균 = mean(차이, na.rm = TRUE))
```

```{r}
kovo_team %>%
  group_by(남녀부, 시즌) %>%
  summarise(리시브_효율 = (sum(리시브_정확) - sum(리시브_실패)) / sum(리시브_시도),
            .groups = 'drop') %>%
  mutate(차이 = 리시브_효율 -lag(리시브_효율)) %>%
  drop_na() %>% 
  summarise(차이_평균 = mean(차이))
```

```{r}
kovo_team %>%
  group_by(남녀부, 시즌) %>%
  summarise(리시브_효율 = (sum(리시브_정확) - sum(리시브_실패)) / sum(리시브_시도)) %>% 
  mutate(차이 = 리시브_효율 -lag(리시브_효율)) %>%
  drop_na() %>% 
  arrange(차이)
```

