---
title: "Chapter 3"
engine: knitr
---

```{r}
pacman::p_load(tidyverse, here)

here('data', 'kbo_batting_qualified.csv') %>%
  read_csv() %>%
  as_tibble() -> batting
```

```{r}
ggplot(data = batting)
```



```{r}
ggplot(data = batting, mapping = aes(x = avg)) +
  geom_histogram()
```

```{r}
ggplot(batting, aes(avg)) +
  geom_histogram()
```

```{r}
batting %>%
  ggplot(aes(avg)) +
  geom_histogram()
```

```{r}
batting %>%
  ggplot(aes(avg)) +
  geom_histogram(binwidth = .001)
```

```{r}
batting %>%
  ggplot(aes(avg)) +
  geom_histogram(bins = 30, fill = "gray", color = "red")
```

```{r}
colors()
```

```{r}
batting %>%
  ggplot(aes(avg)) +
  geom_histogram(
    bins = 30,
    fill = rgb(0.325, 0.750, 0.830),
    color = "white"
  )
```

```{r}
rgb(0.324, 0.750, 0.830)
```

```{r}
batting %>%
  ggplot(aes(avg)) +
  geom_histogram(bins = 30, fill = "#53bfd4", color = "white")
```

## Bar

```{r}
batting %>%
  ggplot(aes(throw_bat)) +
  geom_bar()
```

```{r}
batting %>%
  ggplot(aes(
    x = throw_bat,
    y = after_stat(count)
  )) +
  geom_bar()
```

```{r}
batting %>%
  ggplot(aes(
    x = throw_bat,
    y = ..count..
  )) +
  geom_bar()
```

```{r}
batting %>%
  ggplot(aes(throw_bat)) +
  stat_count()
```

```{r}
batting$throw_bat %>%
  table()
```

```{r}
tribble(
  ~throw_bat , ~count ,
  "우양"       ,     30 ,
  "우우"       ,   1001 ,
  "우좌"       ,    155 ,
  "좌좌"       ,    435
) -> bar_example
```

```{r}
# bar_example %>%
#   ggplot(aes(
#     x = throw_bat,
#     y = count
#   )) +
#   geom_bar()

bar_example %>%
  ggplot(aes(x = throw_bat, y = count)) +
  geom_col()  # Use this when y is already in your data
```

```{r}
bar_example %>%
  ggplot(aes(throw_bat, count)) +
  geom_bar(stat = "identity")
```

```{r}
bar_example %>%
  ggplot(aes(throw_bat, count)) +
  geom_col()
```

```{r}
bar_example$throw_bat
```

```{r}
bar_example$throw_bat %>%
  as_factor()
```

```{r}
bar_example$throw_bat %>%
  as_factor() %>%
  fct_relevel("우우", "좌좌", "우좌", "우양")
```

```{r}
bar_example$throw_bat %>%
  fct_reorder(bar_example$count)
```

```{r}
bar_example %>%
  ggplot(aes(
    x = throw_bat %>% fct_reorder(count),
    y = count
  )) +
  geom_col()
```

```{r}
bar_example %>%
  ggplot(aes(
    x = throw_bat %>% fct_reorder(count, .desc = TRUE),
    y = count
  )) +
  geom_col()
```

```{r}
bar_example %>%
  ggplot(aes(
    x = throw_bat %>% fct_reorder(-count),
    y = count
  )) +
  geom_col()
```

```{r}
batting %>%
  ggplot(aes(x = throw_bat %>% fct_infreq())) +
  geom_bar()
```

## Line

```{r}
batting[batting$rank == 1, ]
```

```{r}
batting[batting$rank == 1, ] %>%
  ggplot(aes(
    x = year,
    y = avg
  )) +
  geom_line()
```

```{r}
batting[batting$rank == 1, ] %>%
  ggplot(aes(
    x = year,
    y = avg
  )) +
  geom_line(lwd = 1)
```

```{r}
batting[batting$rank == 1, ] %>%
  ggplot(aes(
    x = year,
    y = avg
  )) +
  geom_line(linetype = "dashed")
```

```{r}
batting[batting$rank == 1, ] %>%
  ggplot(aes(
    x = year,
    y = avg
  )) +
  geom_line(lty = 2)
```

```{r}
here('data', '2020_ryu.csv') %>%
  read_csv() %>%
  as_tibble() -> ryu
```

```{r}
ryu %>%
  dim()
```

```{r}
ryu %>%
  names()
```

```{r}
ryu %>%
  ggplot(aes(
    x = pitch_name %>% fct_reorder(release_speed),
    y = release_speed
  )) +
  geom_point()
```

```{r}
ryu %>%
  ggplot(aes(
    x = pitch_name %>% fct_reorder(release_speed),
    y = release_speed
  )) +
  geom_jitter()
```

```{r}
ryu %>%
  ggplot(aes(
    x = pitch_name %>% fct_reorder(release_speed),
    y = release_speed
  )) +
  geom_violin() +
  geom_jitter(alpha = .2)
```

```{r}
ryu %>%
  ggplot(aes(
    x = pitch_name %>% fct_reorder(release_speed),
    y = release_speed
  )) +
  geom_boxplot()
```

```{r}
ryu %>%
  ggplot(aes(x = plate_x, plate_z)) +
  geom_point()
```

```{r}
ryu %>%
  ggplot(aes(x = plate_x, plate_z)) +
  geom_point() +
  facet_grid(~pitch_name) +
  coord_fixed()
```

```{r}
ryu %>%
  ggplot(aes(x = plate_x, plate_z)) +
  geom_density_2d_filled() +
  facet_grid(stand ~ pitch_name) +
  coord_fixed() +
  guides(fill = FALSE)
```

```{r}
ryu[ryu$pitch_name %in% c("4-Seam Fastball", "Changeup"), ] %>%
  ggplot(aes(x = plate_x, plate_z)) +
  geom_density_2d_filled() +
  annotate(
    geom = "rect",
    xmin = 1,
    xmax = -1,
    ymin = 1,
    ymax = 3,
    color = "white",
    alpha = .1,
    linetype = "dashed"
  ) +
  facet_grid(pitch_name ~ stand) +
  coord_fixed() +
  guides(fill = FALSE)
```

```{r}
batting %>%
  ggplot(aes(x = avg, y = obp, shape = throw_bat)) +
  geom_point()
```

```{r}
ryu %>%
  ggplot(aes(x = release_speed)) +
  geom_density(fill = "gray75")
```

```{r}
ryu %>%
  ggplot(aes(x = release_speed)) +
  geom_density(fill = "gray75") +
  facet_grid(pitch_name %>% fct_reorder(-release_speed) ~ .)
```

```{r}
tibble(x = -5:5) %>%
  ggplot(aes(x = x)) +
  geom_function(fun = dnorm)
```

```{r}
tibble(x = -5:5) %>%
  ggplot(aes(x = x)) +
  geom_area(stat = "function", fun = dnorm)
```

```{r}
tribble(
  ~response               , ~value ,
  "이름 짓기"                 ,     49 ,
  "개발 가능 혹은 불가능한 사항 설명하기" ,     16 ,
  "개발 작업이 끝나는 시간 산정하기"    ,     10 ,
  "다른 사람과 함께 일하기"         ,      8 ,
  "다른 개발자 코드 작업하기"        ,      8 ,
  "내가 수긍 못할 기능 구현하기"      ,      3 ,
  "문서 작성"                 ,      2 ,
  "테스트 작성"                ,      2 ,
  "해법 찾기"                 ,      2
) -> developers_chore
```

```{r}
developers_chore %>%
  ggplot(aes(
    x = response %>% fct_reorder(value),
    y = value
  )) +
  geom_col()
```

```{r}
developers_chore %>%
  ggplot(aes(
    x = response %>% fct_reorder(value),
    y = value
  )) +
  geom_col() +
  geom_text(aes(label = value), nudge_y = 2) +
  coord_flip()
```

```{r}
developers_chore %>%
  ggplot(aes(
    x = "",
    y = value,
    fill = response %>% fct_reorder(value)
  )) +
  geom_col(width = 1) +
  coord_polar(theta = "y")
```

```{r}
batting[batting$rank == 1, ] %>%
  ggplot(aes(
    x = year,
    y = avg
  )) +
  geom_line() +
  ylim(.350, .420)
```

```{r}
batting[batting$rank == 1, ] %>%
  ggplot(aes(
    x = year,
    y = avg
  )) +
  geom_line() +
  coord_cartesian(ylim = c(.350, .420))
```

